Base Navbar and main banner
Thekote/Ecommerce42 pull request #19
Opened 2021-11-04 14:20 UTC by menezesmario

2021-11-04 22:39 UTC, Lukazovic commented
O PR não está ruim não, tem commits curtos e bem separados. O nome da branch está bem bom 👏🏽 

Dicas antes de revisar o código:
- Como o projeto tem frontend e backend juntos, tenta adiconar alguma info que diga isso. Ou adiciona alguma tag, ou no nome do PR adiciona "[Frontend]" antes, só para ajudar;
- Como é task de front, curto adicionar um print ou video do que foi alterado, frontend geralmente é bastante visual, e ver o que foi mudado já ajuda muito;
- Vi que tem algumas issues para tasks, é legal mencionar qual issue esse PR pertence, para ajudar a dar contexto para quem revisa;
- Da para adicionar descrição no PR, se achar que faz sentido para quem está revisando;
- Achei muito legal que separou bem os commits, uma dica é que por padrão a gente costuma adicionar alguns prefixos aos commits, para saber se algo foi alterado, adicionado, corrigido, etc. Exemplo:
    - "**add** navbar with hamburguer menu (responsive)"
    - "**add** background to hero banner"
    - "**fix** hero banner height"

2021-11-04 23:26 UTC, arthursakemi commented on frontend/src/App.js
> +    <Container>
aqui, você poderia fazer o retorno direto pela arrow, sem a necessidade do `return` (não precisa alterar, é só mais um modo de fazer para componentes mais simples)

```javascript
const App = () => (
  <Container>
    <Navbar />
    <HeroBanner />
  </Container >
);
```

2021-11-04 23:26 UTC, arthursakemi commented on frontend/src/components/HeroBanner.js
> +    height: 50vh;
toma cuidado aqui para definir as coisas com `vh`, por exemplo, abrem seu app em um monitor 24" 4k, vc quer mesmo que seu banner ocupe metade da tela? pode ficar desproporcional, normalmente deixamos o banner crescer de acordo com o conteúdo dele.
porém se for isso mesmo que você quer, sem problema nenhum

2021-11-04 23:26 UTC, arthursakemi commented on frontend/src/index.css
> +  padding: 0;
eu adicionaria também um `box-sizing: border-box;`

2021-11-04 23:26 UTC, arthursakemi commented on frontend/src/index.css
> +  padding: 0;
Como você está usando styled-components, você pode criar esse mesmo arquivo de css global com

``` javascript
//src/global.js
import { createGlobalStyle } from 'styled-components';

export dafault createGlobalStyle`
 // seu css global
`;
```

depois só importar e adicionar no seu App.js o global style `import GlobalStyle from './global'`; e `<GlobalStyle />` dentro do componente

2021-11-04 23:28 UTC, arthursakemi commented
Como o lucas disse, o PR está muito bom mesmo, só levantei alguns pontos aqui que são possíveis melhoras,

2021-11-05 01:15 UTC, marmitoTH commented on frontend/src/components/HeroBanner.js
> +    height: 50vh;
Uma coisa que você pode fazer pra resolver esse problema mencionado pelo Arthur é utilizar a função clamp:
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()

Com ela você pode garantir com o tamanho fique dentro de uma margem controlável, nem muito grande e nem muito pequeno. Você também pode usar min e max com uma finalidade parecida: 
https://developer.mozilla.org/en-US/docs/Web/CSS/min()
https://developer.mozilla.org/en-US/docs/Web/CSS/max()

2021-11-05 12:48 UTC, leossantiago commented
Como o pessoal já cobriu praticamente tudo importante, não vou entrar em detalhes técnicos. Meu único comentário é sobre alguns arquivos que fazem parte da PR:

`frontend/src/components/Navbar/NavbarElements.js`
`frontend/src/components/Navbar/index.js`

São arquivos vazios. O ideal é que vc deixe a PR enchuta, com código que vai realmente ser utilizado de alguma forma. Isso vale pra arquivos, dependencias etc etc. Mesmo que vc planeje utilizá-los, o ideal é adicionar somente quando for realmente usar.

2021-11-05 12:50 UTC, Isaius commented
Um ótimo PR, sem dúvidas. 
Única coisa que posso adicionar aqui é que tente se manter com as mensagens de commit em um único idioma, de preferência o inglês como você já fez na maioria.

2021-11-05 15:32 UTC, Lukazovic requested changes

2021-11-05 15:32 UTC, Lukazovic commented on frontend/src/components/Navbar.js
> +            <Logo href="">
Da para já adicionar o `href` certo aqui para sempre mandar o usuário para o home:
```suggestion
            <Logo href="/">
```

2021-11-05 15:32 UTC, Lukazovic commented on frontend/src/components/Navbar.js
> +    position: relative;
Acredito que falte uma cor de fundo no Header mobile, olha como está:

 ![screencapture-localhost-3000-2021-11-05-12_18_05](https://user-images.githubusercontent.com/54550926/140535237-a370a9f9-4e1f-4158-ac46-fcdf39e4286d.png)

Acredito que adicionando uma cor aqui, já da uma melhorada:
```suggestion
    position: relative;
    background: white;
```

2021-11-05 15:32 UTC, Lukazovic commented on frontend/src/components/HeroBanner.js
> +    background: url(https://www.enjoyintercambio.com/wp-content/uploads/2016/10/festival_cocktail_irlanda_enjoy_intercambio.jpg);
Essa imagem está com 3.9MB, está muito pesada para ser renderizada em sites. Isso da muito diferença para quem tem uma internet um pouco ruim, e pior ainda para quem usa 4G. Até aqui para mim deu para perceber uma pequena demora no carregamento da imagem.

Geralmente da para usar imagens com tamanho até uns 300KB (talvez 200KB). Eu curto usar o site https://tinypng.com/ para diminuir o tamanho das imagens. Na parte free, ele não comprime tanto quanto poderia, mas já da uma grande melhorada nessa parte.

Aqui um exemplo dessa imagem comprimida com 295.6 KB:
![festival_cocktail_irlanda_enjoy_intercambio (1)](https://user-images.githubusercontent.com/54550926/140536342-6fa92289-beb9-4f10-8606-82fc0698fcf9.jpg)

Fiz o upload da imagem para o https://imgur.com/, e da para usar essa URL já com a imagem comprimida:
```suggestion
    background: url(https://i.imgur.com/tFklJI9.jpg);
```

2021-11-05 15:39 UTC, Lukazovic commented on frontend/src/components/HeroBanner.js
> +    background: url(https://www.enjoyintercambio.com/wp-content/uploads/2016/10/festival_cocktail_irlanda_enjoy_intercambio.jpg);
Da até para colocar essa imagem dentro da pasta `public` e chamar ela direto no código.

Exemplo, se o nome do arquivo for "banner.png", na pasta public (`/public/banner.png`), você consegue chamar no código assim: `/banner.png`.

Da para criar uma pasta "imagens" dentro da pasta `public`, para separar melhor as suas imagens, aí você usaria no código assim: `/imagens/banner.png`.

2021-11-08 19:24 UTC, menezesmario commented
Brigadão, @Lukazovic, @arthursakemi , @leossantiago , @Isaius  . O lance da imagem e vários detalhes de design realmente não tinha mexido ainda, queria só testar por enquanto. Queria fazer essa primeira pra destravar algumas coisas de git :) A ajuda do Guilherme foi fundamental. Agora já entendi melhor o processo, vou tentar fazer as próximas mais finalizadas. 
Valeu demais pelos comentários!

2021-11-10 15:41 UTC, merged