Frontend Home (home style correction and product list)
Thekote/Ecommerce42 pull request #25
Opened 2021-11-16 20:58 UTC by menezesmario

Navbar correction (color, logo, resize icons with products in cart)
![image](https://user-images.githubusercontent.com/12040783/142063917-f648dd41-849e-4ce7-8018-fde41439123d.png)

search bar position and banner model
![image](https://user-images.githubusercontent.com/12040783/142064152-c6bf7998-4b20-4524-aa8c-d09ee7abe3d4.png)

Product list
![image](https://user-images.githubusercontent.com/12040783/142064370-6a1b6a3d-a98f-403d-ac87-4c0395d31a0e.png)

2021-11-17 12:39 UTC, Isaius requested changes
Sobre o arquivo de estilo `src/global.js` acho que esse nome está errado, não representa bem o que ele é. Recomendo criar uma pasta `src/styles` ou pelo menos renomear para `globalStyles.js`

2021-11-17 12:39 UTC, Isaius commented
Bom termos imagens dessa vez! Ajuda bastante.
Olhando as mudanças já tá dando pra notar que os componentes estão começando a ficar bagunçados com essa junção de lógica + estilos no mesmo arquivo. Recomendo muito mesmo que comece a separar um do outro. Isso é ok por enquanto, mas já vai pensando nisso,

2021-11-17 12:54 UTC, merged

2021-11-17 16:18 UTC, Isaius commented
@menezesmario você não deveria realizar o merge de PR com mudanças requisitadas sem alguma justificativa.

2021-11-18 19:20 UTC, menezesmario commented
@Isaius não me lembro de ter megeado essa PR, achei que tinha mergeado só a Footer, que foi que o Léo havia aceitado. Se foi eu mesmo foi sem querer. Fiquei um pouco confuso agora.


> @menezesmario você não deveria realizar o merge de PR com mudanças requisitadas sem alguma justificativa.